language: ruby
rvm:
  - 2.3.3
gemfile: Gemfile
after_install: gem list
script:
- git config --global user.name "Travis Test"
- git config --global user.email "travis@mailinator.com"
- bundle exec cucumber
notifications:
  irc:
    - "irc.freenode.org#asciibinder"
